# Generated by Django 4.1.6 on 2023-03-08 11:30

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=20)),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockex.state')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.TextField(max_length=20)),
                ('regDateTime', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(max_length=builtins.max)),
                ('profileImage', models.ImageField(upload_to='media/images')),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockex.city')),
            ],
        ),
    ]
