# Generated by Django 4.1.6 on 2023-03-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0002_city_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='client',
        ),
    ]
