# Generated by Django 4.1.6 on 2023-03-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0003_rename_user_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
