# Generated by Django 4.1.6 on 2023-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0006_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.TextField(default='', max_length=20),
        ),
    ]
