# Generated by Django 4.1.6 on 2023-03-08 11:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0008_user_cityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=builtins.max, null=True),
        ),
    ]
