# Generated by Django 4.1.6 on 2023-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0010_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
