# Generated by Django 4.1.6 on 2023-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0011_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
