# Generated by Django 4.1.6 on 2023-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0012_user_regdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
