# Generated by Django 4.1.6 on 2023-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0013_user_dob_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('prodtitle', models.TextField(max_length=100)),
                ('brand', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
                ('mandate', models.DateField(null=True)),
                ('adddate', models.DateField(null=True)),
                ('auctdate', models.DateField(null=True)),
                ('auctienddate', models.DateField(null=True)),
            ],
        ),
    ]
