# Generated by Django 4.1.6 on 2023-03-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0016_category_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catid',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catname',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tranDate',
            new_name='transaction_Date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tranTime',
            new_name='transaction_Time',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tranamount',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tranid',
            new_name='transaction_id',
        ),
    ]
