# Generated by Django 4.1.6 on 2023-03-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0017_rename_catid_category_categoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.product'),
        ),
    ]
