# Generated by Django 4.1.6 on 2023-03-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0019_save_pvideos_pimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('DateTime', models.DateTimeField(null=True)),
                ('answer', models.TextField(max_length=500)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.product')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('complaintDateTime', models.DateTimeField(null=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.product')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.user')),
            ],
        ),
    ]
