# Generated by Django 4.1.6 on 2023-03-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0020_questions_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_Date', models.DateField(null=True)),
                ('transaction_Time', models.TimeField(null=True)),
                ('transaction_amount', models.TextField(max_length=20)),
                ('status', models.TextField(max_length=10)),
                ('fromUserid', models.IntegerField()),
                ('toUserid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pimages',
            name='imageurl',
            field=models.ImageField(default='default.jpg', upload_to='media/video'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_bid',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='pvideos',
            name='videourl',
            field=models.ImageField(default='default.jpg', upload_to='media/video'),
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Stockex.product'),
        ),
    ]
