# Generated by Django 4.1.6 on 2023-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0021_usertransaction_pimages_imageurl_product_min_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='adddate',
        ),
        migrations.AddField(
            model_name='product',
            name='pimg',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaintDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productbid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productbid',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='fromUserid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='toUserid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_amount',
            field=models.IntegerField(default=0),
        ),
    ]
