# Generated by Django 4.1.6 on 2023-03-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0023_product_adddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimages',
            name='price',
            field=models.TextField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='pimages',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.user'),
        ),
    ]
