# Generated by Django 4.1.6 on 2023-03-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0024_pimages_price_pimages_userid_product_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='pimages',
            name='imageurl',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
