# Generated by Django 4.1.6 on 2023-03-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0025_product_price_alter_pimages_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.category'),
        ),
    ]
