# Generated by Django 4.1.6 on 2023-03-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0026_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimages',
            name='price',
        ),
    ]
