# Generated by Django 4.1.6 on 2023-03-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0027_remove_pimages_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvideos',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stockex.user'),
        ),
    ]
