# Generated by Django 4.1.6 on 2023-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0028_pvideos_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selectedBidId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
