# Generated by Django 4.1.6 on 2023-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockex', '0029_product_selectedbidid_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selectedBidId',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
